name: Sync Leetcode
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync LeetCode
        uses: Priyanshujoshi7/leetcode-sync-sql-too@master
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          verbose: true
          sync-from: "2020-01-01"
          filter-duplicate-secs: "0"
